apiVersion: v1
kind: Secret
metadata:
    name: gitea-oauth
    namespace: woodpecker-ci
stringData:
    client-id: ENC[AES256_GCM,data:goNkxafJK5Vrq09Re4gaeVIIvgLY8PFSXbOlzMQjaKaGOhbe,iv:l/dU6jXDTNUnvlg3t7/uIvHqGbUUf6EYkxr+ShzJkQs=,tag:6emLxsTcZP+y0+gwJ7/DhQ==,type:str]
    client-secret: ENC[AES256_GCM,data:tq6xZepJlNmAMP8xYXyMe1sfPXF3dn2aRDJ/TpcDJ88/l4cHKEPwW4cxLUL/JSzJaPLUYTEnQMs=,iv:1Tsh9iyVrJ9n6UfcPuFh6UTn3erDxd/mjDN8sKbTrBw=,tag:VXm36B+7I9Pwy7V7yfk+rg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Qlg3OTNuMFh0aU5Ic3pu
            SEtDZDB0NWFzYlRSVWVvTTQwaS90Y1NrOGpzCnZMakIvVi9KTHU2YXhPcW8xS1Zj
            ait1MytxcEpIQWsvSzJTT29KdkJ2cFEKLS0tIGVEN2hMVDEyVzlMNThnSHgzcmV0
            SnpSY0VoUG1mL0haMWRGdVZLU1FWbVEK2hbJnU2SkH7UyNOAq03pXESU/L5DWXcP
            oPAgJo7JzQ9NhJjsHFHouDcst+Dqz9ncNOIa3otiJ6n0h22D0KeOYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-10-10T19:21:40Z"
    mac: ENC[AES256_GCM,data:H53NJ78noD4cMtE2sSgvBE667c+DXyA0PBbUS7nbO+8ZvUY8P34MkAvB2RiAZY32U35X6rTPJ9q/HrKzSDo8MrYCf6FKa7H8th4TiMwvXsTAiyI9Xp48j/rtENxeunwcd7pXiz+E3Fl6/D5T1aH3O4pp3QQhXVWuZ19dspui+5Y=,iv:R6TRQTqFyn2vHsEAK8OkB7C0+aUKAjB3BblKc5yhp+M=,tag:qsGDkxCmF5SEunauE1goWQ==,type:str]
    version: 3.13.3
