apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_TAILSCALE_KEY: ENC[AES256_GCM,data:eElEBUKVu+N6vFrXtwtfLhe7KJYm3c5AvM0iyWH4z+N6mPuCakmCZlp7z96tHWSws7q8XN4Dknns2Xey2A==,iv:xmiOQWQ8RE4vMnWmA4/rFcKNMfUXy34HwbydNypEPpc=,tag:iLnpTXO0vFbRRWw9pR7XoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTGZXMDBSQkQ5bGxBTjJw
            VFFyb3c0M25LRWxXOHZRYmlOTnFpditVR0NzCjdVQkdRTkRQbkdsUzIzVXZ3dTRS
            c1VxcGc2MkpTWnM0blFEMzk1SnhHalkKLS0tIHBIU2hDb0pTVnk3cmNvMXFSdlVS
            YWtlb2w4UGl6cmtLcWlFRHkwM0R5U2MKgE6IrWUunyypijvoZ9KDbJJymGE7ronr
            4yB01eMbrz/ZDrvdP/H2hvUdGTf4aNTVWi2EUYWpdtGDeoVwGvXZvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-10-03T06:47:55Z"
    mac: ENC[AES256_GCM,data:2eI+QUMlRetrcEh5wmvwtRAa2QydubUq7gbcdCxYM0ZrZ4xu25+zAeqigEdGfL78xdMMN9dZ4XI/MLtM6YWAduigaHXebnR7PQzpKh358gnC3sjSGtPGhkonCGk9O7AWKAwp7qpt8CfboGBqNH2NQ4QB29a2mWFTtFGVOHaXAtY=,iv:FthjZQpA8fJvpAf4h0v+QQIETKiURJabUuDP4++26Yo=,tag:KL7T2ahPMiN/eksCzPmYnw==,type:str]
    version: 3.13.3
