apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_TAILSCALE_KEY: ENC[AES256_GCM,data:ipwqdGLy6wzh1Z/yckF7x4zgHi53hMHVL/2V8Y4czXE6xc5z3R8GGS5E9F9ncS0oxnBW/kdvIyqF7xPi,iv:rexudE6D8xjXQK4CLhNofdNtEX2wY9f/XLGlmz6TzJs=,tag:ScqNDKB1iSkyRVfIhuB4vA==,type:str]
sops:
    age:
        - recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYmVFbUNZKzJpUCsxUlRt
            aFF1MkxOT2lpbFVScWQwcDk1UVVnUWtSSnpFCldxYThkbktuSjFmREZBYnowc2hx
            OHc4TnFNdzRteE1mT0hyQktRMmZsZXMKLS0tIE9aYTJJZHdGRGtseDB0Rk1iY2Zw
            cVM0eTZYbTJhYzBMWUp0MFZidFRYQkkKCY5g5YKHdiLi9buGLcM6mv02DYqPx3B5
            kMEnp/7U8XIbiOqEw+GpqltXgQPBYYquiQ5xO/+GuXQGSzapW1jHPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T05:58:41Z"
    mac: ENC[AES256_GCM,data:ZTjC9S4KAT96nU94/MpL1ELE3sA81Bcnjsc2zNMvwpNjh1am4AkUgFLHTmh5Ay5oelXAcTARm6x3r4rl11jaZX6nvWHX1PYusR0g58xnrtFk0v9AZx2CkzMDkd9NMj+gyTOFjyMjqt+RJLbtcF9L4NuzQwd2aSQ3ghdnLL9UPhc=,iv:AAdEyyQigo96jvnuQ54kIoEPTNHLTd3qCqPzlX04LhE=,tag:enu+ESbHSj36W0Zb9AJZKg==,type:str]
    encrypted_regex: ^(data|stringData)
    version: 3.12.2
