apiVersion: v1
kind: Secret
metadata:
    name: soft-serve-admin-key
    namespace: git
type: Opaque
stringData:
    admin_keys: ENC[AES256_GCM,data:x7n4C0qGsntgE1O1nAFDfAPJQWxgu3L+hvg1imAclY1LHc7Icb7ETB4s5Qf8gVCp8j94zhFKKSRtcsy8q18UF6yu9e73FGUr7pWg72yybNbMudrRVRT90xGARq1HPog/ZvMJ/jr9,iv:40+Om1pgyTQz1DR/3bNQV9jm7zO1LoNdjbELQkjWofw=,tag:6CneMq3n2g+Rg0KEaYeyRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cnNKUnNERnRDWlBoaHBq
            SU5uOEdmTG11TzhWRkExa29BSUdoa2RwWmd3Cnl5L1pPbEVHM1lOMDF2Z2RVM2o2
            eUI1cU42aGI3UGUzWWk2U0VQSUloWXMKLS0tIFV6cDBqeTRObEw3NSs4dERMSFRr
            Q3FhODV2c1YxdkhlWXhxU0hsYjlYNG8KQPvrvHJimiUE3BfM71N2up8rTHwADlHa
            zPdOTiYjV98vvKwuVlksDcEcLR/QUKYBd9IswQQPhiFeoBaw1YoWlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-08-28T14:12:44Z"
    mac: ENC[AES256_GCM,data:u8jA85E0aMFHo1yRool32cSHqwNm26ucIPn31zdbH5OvMNIis6/p4maTyYdw5oT/Hnu0XFXdKqtO2fa0eR5NzPIEK4ZgXZz8s48cg0hL4yCIzDnZhlsgLTyz23G4N3vaOQv4FZEcjQ+QrWhEnvVAIH6ddRz5qHs9wTjGYBgtEEA=,iv:Dw4mgGvMvyqf4FU5lYBYRoK+yxfatWwsWLdDM+Ag8aQ=,tag:l5tJ8VUSpIQKxGtVQyUFfw==,type:str]
    version: 3.13.3
