apiVersion: v1
kind: Secret
metadata:
    name: soft-serve-admin-key
    namespace: git
type: Opaque
stringData:
    admin_keys: ENC[AES256_GCM,data:gv7qmtgTt+bVyJP7JEMtAMqCs0lEm9kcUAoi0z6NJ/e6YOOnprKeeCRhGSc8g+JmPoUsWz7N8sEXMDX4TP3uTbWgetQigbUpK0tgOtuMstT8mCeRKU3Rbf7XNzy9A/ifqoZGGbMU5dg=,iv:oWo4gAKwqGKGSzALAe2wYLV6qWAbs2LLzMqZPCVjkSY=,tag:yYNguzAbLLi6SLLPmeosbw==,type:str]
sops:
    age:
        - recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QTVLY29nek4yV3JqYWUw
            ZGl4bnhUN0tYT0taT1lzWWpsNEJBek91RDFJClRRZjFzMDNaOXEwU1RVNmRFa3hi
            SGQ4QllwQTFwVHFqcjQ1R3U2am1XRjgKLS0tIGsrSUt0c2FDL29Uc3FGSFdsOTFw
            OTZZQTVMRHJQcXZ0T1R0bTBnN2NZNEkKYMDg/30ouv2/zVZe2c6pMM0qBfOLyJaF
            P5Wro9Va+3dlznbdZjNyaizhowQgJJRaRwB/pVPFL4Y1NtKQzQhypQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T16:24:09Z"
    mac: ENC[AES256_GCM,data:DRGcrhDrNYO6zeWxCd+Gq0V4xWz5ETeCq9tHcR7J3tXpcvTInOCJNKfU174+MxZJXfyYe2wtCdMdzR2WD4Y+n6+xdbecagBTDDlCsyXb3FFQh/YCYZWBCQzvkKX637z+5wVs/ONWk8mDzvpPnZzGUnxGQjkEs/xqYUpg10XZp/k=,iv:NW8yQVXGQT0DVdUYsCeDFtgnxcgjmtKmb3ZBB12/oBo=,tag:otJS/Xh8QdBp6O1Lmyodyg==,type:str]
    encrypted_regex: ^(data|stringData)
    version: 3.12.2
