apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 30m
  releaseName: gitlab
  targetNamespace: gitlab

  chart:
    spec:
      chart: gitlab
      version: "10.0.0"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: gitlab
      interval: 1h

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    global:
      hosts:
        domain: tail36f6a3.ts.net
        https: true

      ingress:
        enabled: true
        class: tailscale
        provider: ""
        configureCertmanager: false
        tls:
          enabled: true

    nginx-ingress:
      enabled: false

    certmanager:
      install: false

    installCertmanager: false

    certmanager-issuer:
      email: ""

    postgresql:
      install: true

    redis:
      install: true

    prometheus:
      install: false

    gitlab-runner:
      install: false
