apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 30m
  releaseName: gitlab
  targetNamespace: gitlab

  chart:
    spec:
      chart: gitlab
      version: "10.0.0"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: gitlab
      interval: 1h

  install:
    timeout: 120m
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    timeout: 120m
    remediation:
      retries: 3

  values:
    global:
      hosts:
        domain: tail36f6a3.ts.net
        https: true

      gatewayApi:
        enabled: false
        configureCertmanager: false
        installEnvoy: false


      ingress:
        enabled: true
        class: tailscale
        provider: ""
        configureCertmanager: false
        tls:
          enabled: true

      appConfig:
        object_store:
          enabled: true
          proxy_download: true
          connection:
            secret: gitlab-object-storage
            key: connection

        artifacts:
          bucket: gitlab-artifacts
        lfs:
          bucket: gitlab-lfs
        uploads:
          bucket: gitlab-uploads
        packages:
          bucket: gitlab-packages

      registry:
        bucket: gitlab-registry

      psql:
        host: ep-delicate-breeze-aqkuxwuy.c-8.us-east-1.aws.neon.tech
        port: 5432
        database: neondb
        username: neondb_owner
        password:
          secret: gitlab-database
          key: psql_password

      redis:
        host: exact-flamingo-135298.upstash.io
        port: 6379
        scheme: rediss
        auth:
          enabled: true
          secret: gitlab-database
          key: redis_password

    registry:
      storage:
        secret: gitlab-registry-storage
        key: config

    gitlab:
      gitlab-exporter:
        image:
          repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-exporter
          tag: v19.0.0
      toolbox:
        backups:
          objectStorage:
            config:
              secret: gitlab-backup-storage
              key: config

    nginx-ingress:
      enabled: false

    installCertmanager: false
