apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage
    namespace: gitlab
type: Opaque
stringData:
    connection: ENC[AES256_GCM,data:xBYOIGItGY95oKxO5HiT6BAPsLTCcePBCfRPchNPYO01amf0CayQdFUC11Wxew7vVfl1N7Xeseye3YXbvoBZVh7/5c4PHY61a9a5u/TPloI1+BJJxt1q+TRUKzGsFbm7FLn9wKI0HTnyP+ojtRQUDXhFVGgm+wMBLV9W5MiKAR0fMxXYoRwVD5cmrN/l/rMOJa45i18Lp/htf7oIQVoLP0WCzywbFaDnh1+bN6xCzKvHOcY4Up7m7uMQno6/aWZfEC9MVy5FLn1XqeR6rZzhfX7giklOF+DUI0HDyLKRzYc53GmCd8DtFcJtpNaCZ+N7kuxZHKDpZE8n0GpMJ3NRUCrxaVI=,iv:bv9nB5QSzdPnqG7zUdyiqlUuCzo1N6dkQqqSENXEljE=,tag:rqK5n936t5hf+HiqRY6bZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVEcrLzJ5YUNBY0U4YXhJ
            eE5sVldMTEFnRE1id3dTQ2thYVRNWEtUbGpRCnJRcTFhQTNRWjRnUnhZeU9CKytn
            YmlpdEtST0QyaC8xTFZ6d0FXUjhoekUKLS0tIFk2WlZNcTVlZTIrUnZLOGRDSmVT
            am1VeXJ2L3NONkxPcEJzaW9WSnM0clUKSx6eFNMSGIQyoXHjUhXxhMoyXL37GJUW
            5M7r0lXZ0n2GDT8a6Q0wiTn68tfoTwES+Crryf6/xdx1aK39t+KkuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-25T08:03:07Z"
    mac: ENC[AES256_GCM,data:2MCkudIP5dLFPTn2NVjdiTtFHJ39vZRAMKaMJGxTHO0TYLPc4oO7LEoigxOSVUYukeeOXEXPmUPOwFTkSE8uz/p2dnbMUvEi4G8QDyUutHxIkVC1T14/4CsdFUBbYRTO80gGvEHVTctBNh0SEGBlXe7M9mclnfQtr+BUD6vlMOQ=,iv:rcsJqD+0/M9u7M2k06EClrk2I3FL1v81+XTfRep2aJA=,tag:nx0TmQ3wRalLcGCyZkNqsw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:v863Z7us6K4FJtwnSgjWGd/J2WJuDOXJpJnLEv728KTt4cfp3Mh1V1E/g6Q3Mc5I1D78gumq4Q9hhH/xfTBk+CdeLPU1QXA+1Qu81BfQJE9oEagGRgSOwt20PBioML4pv7q6S/wV3t6qTroMz3UTZwQ9LXdZhZYyo/k4CZYs/N676V5bF0umqr+eyPPuX9yVKkOF7v4pN8oMGxBTsTZU0UWGO7GaVQ6k95jQ5JonAt/bbE5u4AF6k/6+e2YpK2d7JAvS7y8wWqahftEqiXbdAlW+5qo7wSCon3VJYBD1SicP7mgKknknu1VU9/1b5XxgCQGoWM0Gqs88OE8ufXZA3ykFyQxF+FsL+hcyLKkym+c4d68wigWMmJ0guwvUQQ==,iv:9wfXkuk15tO3Q5B7D90fvYVIl5/ZRRuRLDpojS5JUUk=,tag:0WAs5ZxFT9hy5zjnE+ohRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVEcrLzJ5YUNBY0U4YXhJ
            eE5sVldMTEFnRE1id3dTQ2thYVRNWEtUbGpRCnJRcTFhQTNRWjRnUnhZeU9CKytn
            YmlpdEtST0QyaC8xTFZ6d0FXUjhoekUKLS0tIFk2WlZNcTVlZTIrUnZLOGRDSmVT
            am1VeXJ2L3NONkxPcEJzaW9WSnM0clUKSx6eFNMSGIQyoXHjUhXxhMoyXL37GJUW
            5M7r0lXZ0n2GDT8a6Q0wiTn68tfoTwES+Crryf6/xdx1aK39t+KkuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-25T08:03:07Z"
    mac: ENC[AES256_GCM,data:2MCkudIP5dLFPTn2NVjdiTtFHJ39vZRAMKaMJGxTHO0TYLPc4oO7LEoigxOSVUYukeeOXEXPmUPOwFTkSE8uz/p2dnbMUvEi4G8QDyUutHxIkVC1T14/4CsdFUBbYRTO80gGvEHVTctBNh0SEGBlXe7M9mclnfQtr+BUD6vlMOQ=,iv:rcsJqD+0/M9u7M2k06EClrk2I3FL1v81+XTfRep2aJA=,tag:nx0TmQ3wRalLcGCyZkNqsw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-backup-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:wkMN7s4QZyAiLtHOl/xbJ5SpoLjdLnQ/1IU+OdU6lo9yXa8QeuSx3hKvvsspIyErNds71BFnHXxfj9Go/kMHjKNmGqvMEjme3XQLO4xDGMqvUX0xzH2/GSIZzTR2krWF3AasMupnK/FkFi5MaUcWei4jSPO81Oqj4XTwlauwZ5THCL8zmDzqwcZUw0Trt94G5p1GH+u6bXvkXrM03ugPHpQo4JhX9DSIsIpz4WQUxY9zI+C6clkEObudnOzOiOPhzn9AqXANtxdGVOPuE0QNt2upliqD4gTSufCzHoZqZKGXwl9D0jtHxK7B2rcupoYCWRwlMEpmyKRmnP4RiABCikakk/egmHBQiMHr3YPZYQpZJiVliW7517GzUVp6b/3JML78S5R4PwIoplDEkMVawFPRLnZlCkCtYvYu8+yOrgUyhTWElslgPfLkXsg=,iv:ge3r7LTIQnuEOMB8qd/mWPFtWnlia2NtfSZksXGTfBw=,tag:C/QSdneboE3qXyh3szvmBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVEcrLzJ5YUNBY0U4YXhJ
            eE5sVldMTEFnRE1id3dTQ2thYVRNWEtUbGpRCnJRcTFhQTNRWjRnUnhZeU9CKytn
            YmlpdEtST0QyaC8xTFZ6d0FXUjhoekUKLS0tIFk2WlZNcTVlZTIrUnZLOGRDSmVT
            am1VeXJ2L3NONkxPcEJzaW9WSnM0clUKSx6eFNMSGIQyoXHjUhXxhMoyXL37GJUW
            5M7r0lXZ0n2GDT8a6Q0wiTn68tfoTwES+Crryf6/xdx1aK39t+KkuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-25T08:03:07Z"
    mac: ENC[AES256_GCM,data:2MCkudIP5dLFPTn2NVjdiTtFHJ39vZRAMKaMJGxTHO0TYLPc4oO7LEoigxOSVUYukeeOXEXPmUPOwFTkSE8uz/p2dnbMUvEi4G8QDyUutHxIkVC1T14/4CsdFUBbYRTO80gGvEHVTctBNh0SEGBlXe7M9mclnfQtr+BUD6vlMOQ=,iv:rcsJqD+0/M9u7M2k06EClrk2I3FL1v81+XTfRep2aJA=,tag:nx0TmQ3wRalLcGCyZkNqsw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-cache-storage
    namespace: gitlab
stringData:
    redis_password: ENC[AES256_GCM,data:N8s0J8H27tpCy11hzYe0MHjRNBXes6Jtf4wxeOM8FHQB3ROE7pp5giBXXuUTb22FXGNJ6N/R/RCreNgBdR4=,iv:NTGXq6ZAXbPMlVF3qZ8Wl28fJHO5+2lZ1nHyiJE83xo=,tag:d8pz6kI3u2gOISx/4K8IJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVEcrLzJ5YUNBY0U4YXhJ
            eE5sVldMTEFnRE1id3dTQ2thYVRNWEtUbGpRCnJRcTFhQTNRWjRnUnhZeU9CKytn
            YmlpdEtST0QyaC8xTFZ6d0FXUjhoekUKLS0tIFk2WlZNcTVlZTIrUnZLOGRDSmVT
            am1VeXJ2L3NONkxPcEJzaW9WSnM0clUKSx6eFNMSGIQyoXHjUhXxhMoyXL37GJUW
            5M7r0lXZ0n2GDT8a6Q0wiTn68tfoTwES+Crryf6/xdx1aK39t+KkuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-25T08:03:07Z"
    mac: ENC[AES256_GCM,data:2MCkudIP5dLFPTn2NVjdiTtFHJ39vZRAMKaMJGxTHO0TYLPc4oO7LEoigxOSVUYukeeOXEXPmUPOwFTkSE8uz/p2dnbMUvEi4G8QDyUutHxIkVC1T14/4CsdFUBbYRTO80gGvEHVTctBNh0SEGBlXe7M9mclnfQtr+BUD6vlMOQ=,iv:rcsJqD+0/M9u7M2k06EClrk2I3FL1v81+XTfRep2aJA=,tag:nx0TmQ3wRalLcGCyZkNqsw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-database-user
    namespace: gitlab
stringData:
    username: ENC[AES256_GCM,data:t4mAefRf,iv:ppVV0MW8AGiCweQH7dlMRw1PLDm2UdV5fQkGLzzADkg=,tag:ttwB6RSYKqjMexyVOUhW+Q==,type:str]
    password: ENC[AES256_GCM,data:2OkOt27IJEo=,iv:V4Jdp6OSPamrK4jY85ZdS9aSBrLyHDKK/L+ebFAnr3s=,tag:BWhxDd1KjdAHLS6SiqhRZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVEcrLzJ5YUNBY0U4YXhJ
            eE5sVldMTEFnRE1id3dTQ2thYVRNWEtUbGpRCnJRcTFhQTNRWjRnUnhZeU9CKytn
            YmlpdEtST0QyaC8xTFZ6d0FXUjhoekUKLS0tIFk2WlZNcTVlZTIrUnZLOGRDSmVT
            am1VeXJ2L3NONkxPcEJzaW9WSnM0clUKSx6eFNMSGIQyoXHjUhXxhMoyXL37GJUW
            5M7r0lXZ0n2GDT8a6Q0wiTn68tfoTwES+Crryf6/xdx1aK39t+KkuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-25T08:03:07Z"
    mac: ENC[AES256_GCM,data:2MCkudIP5dLFPTn2NVjdiTtFHJ39vZRAMKaMJGxTHO0TYLPc4oO7LEoigxOSVUYukeeOXEXPmUPOwFTkSE8uz/p2dnbMUvEi4G8QDyUutHxIkVC1T14/4CsdFUBbYRTO80gGvEHVTctBNh0SEGBlXe7M9mclnfQtr+BUD6vlMOQ=,iv:rcsJqD+0/M9u7M2k06EClrk2I3FL1v81+XTfRep2aJA=,tag:nx0TmQ3wRalLcGCyZkNqsw==,type:str]
    version: 3.13.1
