apiVersion: v1
kind: Secret
metadata:
    name: gitlab-password
    namespace: gitlab
stringData:
    psql_password: ENC[AES256_GCM,data:JmlsR4dE5V9b+IWBBSXs3w==,iv:TszL7iN/oWy47spvCJW/V3nC7Z8139mYg38wH+Zl/m8=,tag:sYO/BRANgkKUcfyLY4/06w==,type:str]
    redis_password: ENC[AES256_GCM,data:BehTegrPJUQjW98odey7XbDZQSylXf5KL8IY3ffVo/N1K4I18nWopT1+VTsOt2LwbJmdN0R23d6iE0DIVcU=,iv:mExdn62/hG0zGwPnzvsCC+vocKMr8tzbA6XtSBDXlP4=,tag:c9Vh0wLAXEhQDef1z1Ihag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrREttdzJrMVk0L0MzUEVq
            U1JaQ3grM2piSE41VDNvSDQrK2hXaFphOUV3ClVoTWNSTzVLS0xxSHdIRUM3WFdi
            MmhVbnlzV0EyWTVSZlJ5M3ZvWGUxKzgKLS0tIGk5M0p3VFZYa3RvS0svK2M2TWYv
            NngxTGI1UVVxcXMzZkJtcnhUcjRXRU0KCGvyKiuc9bbdgIMLnQpdG87FxMq+qRe+
            QOJseWtapBObnFrk0sOQj92wXl7jIvkwBggu03BQjy/iIs81hRe59w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-24T16:56:57Z"
    mac: ENC[AES256_GCM,data:E7sNp5nFI3mYWW+fc6blR1CH55GwEOEVU8uM/umRvvHWcVVX2u45JPqNG4U4ZEbNPJ+273RXcW9ie7dW8bbwZfRVKweTgUQZHMI/rG27YjUww2BneVCREejmVk+n6Q2v+UrMFUsDtnz7QuAOq+OqvkGtx1wcWSkHGzq9vPcF6SI=,iv:ZBlG5lagB7Y2B/cv/f6plEfXFlA9I8VAkLGC1xRsrlM=,tag:Uqv6mAZUFswbTT6zjbJgSQ==,type:str]
    version: 3.13.1
