apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage
    namespace: gitlab
type: Opaque
stringData:
    connection: ENC[AES256_GCM,data:wQEPLo14btAiUiSFK4Vqr2t0X38apjg9GZOkMie87avXJaIBIbvGu9sTG+5+v4mqVpxOxYaYIN2agc7Lh3ddB0PDcQGKq0rhYr+lgosFV/aZmKPY0h/KSn1Ub9U+uPadZLmkj1e4LCHqgi80xEiFtXVeO5xtnEKgXGoKGNNBD/v2WhUovPpw1gujDYn+aAp0OEt0DiBhAKHVZBWBW46MKFRF/OGq3A9m1ZY3DP0OsDcfKdzQI6tYpwNf561mwdC1kArTSe/3PH7BOVSwa+uTGgDPvr62XP1FamCt6U9cFTWQIbvicrjWRZG6ROqyAEl4+VF7CPPcM16AEnFrPfItfeVOUi8=,iv:MrruK+sKn3TYHXzFIUD9RIbo2D4wsetoYdSzO8X4fe0=,tag:lCu87FXjaxUplInlAI2Lqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwLy9pWWo1UzZrUXRPTm56
            Wm1LR2VkTXRkcXZlbEY4RDRiWUxoNmtyanlnCmhPRzNTeFJkd1pkZ005MDVGSEQ5
            eStibE1scDFmeURmaFVKSXBXelFjL28KLS0tIEtEcS9JWmY3dCtHV0pGRFQ5THlE
            Sk1oOFhwRzhSeUpDSmtzeTRldXJPSzAKBx9kAvRMzyaodnB9JOQCn0Bhd3LgOEFS
            UWHhf60wO+o1hRCRqcshS/jtpUzoa1TQmtdsRR0VMdV1L4vQhm3FSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-25T06:34:51Z"
    mac: ENC[AES256_GCM,data:Ns6AStPpwxQxXO5R4htrW5wMRZy5VBXcIb4n8o5zCOGE+1SxdYJZoItNDG6llS7e8ZDfonmyQJYhOTTkS5GRhH4ikF5tOAevec0bM9FXsiToLJfFc3gAcRkNDQPW2GMa9DAjiPne2+VHGhjUe981nsSkkCRsbezg/S/KfI3kxcM=,iv:U5ANODibbbimBCudBCvQq9DHnDW3VnZHHt48BGd/0CU=,tag:4gN42kARwg0ewq05hvpKmw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:tDRQdSLnKg+iAzAX+1e6nyOipvxYKNk2m+xyEbGbX7klSU3lYjY5Fot9zYebslwc2lOcFmbiwBunJeR/sXQX4uPFrO85E+JoJKe9I7XTHe7pGfTQi3dvHr2NDQBXwDs9jpEniW04gDYMG1ygdSDbRxRoxGA3OHCfFuG9NMJYq8hosEopM4G0dYq73T3XfK6jpJk+o/6M2Cn5VRyzULRbD5EhJfhACxdTnwgTZMOFUY44HZZhtHYbq5x/nv5HSYlxvyemKLRcSPT9Y6x8U+XFaxGcj52EcF6ffVNnGHuduth97DsFO9AnuRPwzpS3S+WQSfvenjGo+eMGCDjWFrwOgtanORoDbYZ6hHTJmfPF7+U1o2VntPtCvOSobDCTqg==,iv:iAsl8PMN+nfwBcm/U04IMlcRR8TpN1ndch+fFYsDtTI=,tag:jSDubisDJdirfwuRDuTHAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwLy9pWWo1UzZrUXRPTm56
            Wm1LR2VkTXRkcXZlbEY4RDRiWUxoNmtyanlnCmhPRzNTeFJkd1pkZ005MDVGSEQ5
            eStibE1scDFmeURmaFVKSXBXelFjL28KLS0tIEtEcS9JWmY3dCtHV0pGRFQ5THlE
            Sk1oOFhwRzhSeUpDSmtzeTRldXJPSzAKBx9kAvRMzyaodnB9JOQCn0Bhd3LgOEFS
            UWHhf60wO+o1hRCRqcshS/jtpUzoa1TQmtdsRR0VMdV1L4vQhm3FSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-25T06:34:51Z"
    mac: ENC[AES256_GCM,data:Ns6AStPpwxQxXO5R4htrW5wMRZy5VBXcIb4n8o5zCOGE+1SxdYJZoItNDG6llS7e8ZDfonmyQJYhOTTkS5GRhH4ikF5tOAevec0bM9FXsiToLJfFc3gAcRkNDQPW2GMa9DAjiPne2+VHGhjUe981nsSkkCRsbezg/S/KfI3kxcM=,iv:U5ANODibbbimBCudBCvQq9DHnDW3VnZHHt48BGd/0CU=,tag:4gN42kARwg0ewq05hvpKmw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-backup-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:IbRnX3Y6ykwEA4hWrpkKyHcS0aTXMhVKZO7/JKqQ5yJG/6xE6UWJqING15GKzfGMVs2fFDDiCCd7BpSjcgL/dcypz4N6lU/W5ROvOA91t6XEsd+YduONahZEri7FN1fFuCyeLPlIixawcBctzE1q7oQSa01kdgRlqW6M25g/xz0q/f+5AP1VqkVchmNtd3UU9ELwBaV93plX7L/+XyR9eDbtMOaCVqZfLmHH64pEwExJfXyL9uw+HmImGbGGp5p6cpe3ItNllGrFMe7nDr7HwDCT+dzvYi8JUlvFARj9ANgBCEABP2o+Z4p0nU1nsc9RgkChGIc+bHE6+RnsIcpEZL3LmGdQBA2jxA7cx0++a44QXj4032ougbOfa5XJDisROc19GMg2cDkhprUbxlIxNQC1gGWtPIkSVE8lKpsfmshbgKuNt9VPuPNl7kc=,iv:tOqNr8h68Gix20LJM/yJa9R/4cdDqx3wcS/lI6kqu2U=,tag:zWXOkRsslvuoqomRNcYv2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwLy9pWWo1UzZrUXRPTm56
            Wm1LR2VkTXRkcXZlbEY4RDRiWUxoNmtyanlnCmhPRzNTeFJkd1pkZ005MDVGSEQ5
            eStibE1scDFmeURmaFVKSXBXelFjL28KLS0tIEtEcS9JWmY3dCtHV0pGRFQ5THlE
            Sk1oOFhwRzhSeUpDSmtzeTRldXJPSzAKBx9kAvRMzyaodnB9JOQCn0Bhd3LgOEFS
            UWHhf60wO+o1hRCRqcshS/jtpUzoa1TQmtdsRR0VMdV1L4vQhm3FSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-25T06:34:51Z"
    mac: ENC[AES256_GCM,data:Ns6AStPpwxQxXO5R4htrW5wMRZy5VBXcIb4n8o5zCOGE+1SxdYJZoItNDG6llS7e8ZDfonmyQJYhOTTkS5GRhH4ikF5tOAevec0bM9FXsiToLJfFc3gAcRkNDQPW2GMa9DAjiPne2+VHGhjUe981nsSkkCRsbezg/S/KfI3kxcM=,iv:U5ANODibbbimBCudBCvQq9DHnDW3VnZHHt48BGd/0CU=,tag:4gN42kARwg0ewq05hvpKmw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-database
    namespace: gitlab
stringData:
    psql_password: ENC[AES256_GCM,data:3qdMgfiKKWae6FXGivo=,iv:gh/IkFMb/7Adf1sqCSrmOcbfV4wYaM6a79Zu7MuUIP0=,tag:rWfXsAhe18qOX1BeDDj23g==,type:str]
    redis_password: ENC[AES256_GCM,data:xOEIWCovQqH3+866w3z611uhMXzgTpjYWhDIGljU87THLw+Sdd6SEhewZxVmaeqSnhZS16l4FUT9Xt/Ky4Y=,iv:q0Wfh3IDRqX95EuLmqjyMDyzvoiuG589suzsEaoHAw0=,tag:y1puf1hkLcM+a8iyK6pxvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwLy9pWWo1UzZrUXRPTm56
            Wm1LR2VkTXRkcXZlbEY4RDRiWUxoNmtyanlnCmhPRzNTeFJkd1pkZ005MDVGSEQ5
            eStibE1scDFmeURmaFVKSXBXelFjL28KLS0tIEtEcS9JWmY3dCtHV0pGRFQ5THlE
            Sk1oOFhwRzhSeUpDSmtzeTRldXJPSzAKBx9kAvRMzyaodnB9JOQCn0Bhd3LgOEFS
            UWHhf60wO+o1hRCRqcshS/jtpUzoa1TQmtdsRR0VMdV1L4vQhm3FSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-25T06:34:51Z"
    mac: ENC[AES256_GCM,data:Ns6AStPpwxQxXO5R4htrW5wMRZy5VBXcIb4n8o5zCOGE+1SxdYJZoItNDG6llS7e8ZDfonmyQJYhOTTkS5GRhH4ikF5tOAevec0bM9FXsiToLJfFc3gAcRkNDQPW2GMa9DAjiPne2+VHGhjUe981nsSkkCRsbezg/S/KfI3kxcM=,iv:U5ANODibbbimBCudBCvQq9DHnDW3VnZHHt48BGd/0CU=,tag:4gN42kARwg0ewq05hvpKmw==,type:str]
    version: 3.13.1
