apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage
    namespace: gitlab
type: Opaque
stringData:
    connection: ENC[AES256_GCM,data:sdvzvmsWsFmB2EfWMdeVweOYHAYr11xi1mc8g9TOT/brb5k3LgXcN3Hj5c+6LSJE85IU3a1aCF7MpMUvowoy7hSLUzovUltWPB6KaKiEmcRi8nhAuMpp6vCZJHD/D0VCJF12ky3E2gt8WVLe4S9iYqLo8Qf0RB/nDCkUZG95oJPJdyFTzv8r/SheSUXSLsbRoBEVz3L6D9IO99eTpEVZi11Ikd4EnuWQ6o3t2XP5AhiD9Kz4y+YpT4PFOOqH32ljn7Lz+ibSxPomzncszbZY+ojdyV+GEavnW8Ri0YDBU6ruXvxb02mFl/MbJKqH2h7cwjE+ZeEADnnCzDyifJoYC1IjMaQ=,iv:nb49ucnZVimZLtn6hk85gcG9cAnlJR5nwSUqqUOzYmA=,tag:PnT7+Fxv5TDH6YaLsQT9qA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUmZPcXpBUmw4ZEx6UzVQ
            WllIUlQxa1RORlk1Z2JOYnFzQUpTU1BXNW5nCjEreGd6aHYrL3MzcEhzemw3K08x
            RVl4cm8vQkYxRnl0TFBORlpkR1A5UzQKLS0tIHg3K3JWcW54akJ3WS9yK3dGdk1I
            ZWs2azRHNlY4S3NuRXN2WGtVeUFwSXcKtH4Av+52XbsTP9PEG2hK7WVzHOCAoQ7+
            Jd1KGClEoJ8Yu4V0VbbAu03FDg4GJ70CcHoxWFNqWo2pe/24qRohuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-24T17:12:29Z"
    mac: ENC[AES256_GCM,data:aZUDaue/EJ1s99le3I5SIuapcpc1vXlIvS2N/NfCTp12DtIEEEuMlNzWRimip/PNHz3+NiOVPdY7+p4ZfcNMB6E7AtY2hnBgyeTQKYhFpHUqm/DllwX3yT4rEtosnqEUVz4GBBY4Y7NVTW86afbLBUpJTCpbC1qbz6YXYJR3P3o=,iv:k1dA/5+Wumz/PMuAgEuh0QrUKhzeDO93H/4xouSTLo0=,tag:Eqh+b4O0q4yGBjshDibScg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-registry-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:HzPr/xgNNlGzStde5Osu8XO4pRNM2PScck1YO5cXiqdjTH0P4xemRZHfPWiQRTS6TxI0VQr/KPKGDy+kiWEqFSK6htHp4SbpyNf0Xq0uH/3S2q/yB2CfMhIzwwT4phCxZqg6PaukntXJ5avpJV9UFK1dQXY6JS0kVCBG+rvVdx9CXmF7npq70B1NUhDHDwwAcPAwZl5GHQERJicdayyaPI+LwuGyPynrb0QEhPU2KSV59KgP9lyChPsehGaPfG0LsXQPNxczaHxXUPbo1f9MRx7E0pHuaIdbIkW22wTR17qep/5Va1bPfq22RWv7h+6UjTh1riE3SqtqbD51tKU01HZ6w9twzk/o0+HzOivSD4/ECE3OTeIxQVI7ZnziJA==,iv:M7JaLERAMsqozOU4ibiK3j9+442Yq/hDZ/rs+n+Hb8I=,tag:vKrA7yFoic6K6/IbSx1rIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUmZPcXpBUmw4ZEx6UzVQ
            WllIUlQxa1RORlk1Z2JOYnFzQUpTU1BXNW5nCjEreGd6aHYrL3MzcEhzemw3K08x
            RVl4cm8vQkYxRnl0TFBORlpkR1A5UzQKLS0tIHg3K3JWcW54akJ3WS9yK3dGdk1I
            ZWs2azRHNlY4S3NuRXN2WGtVeUFwSXcKtH4Av+52XbsTP9PEG2hK7WVzHOCAoQ7+
            Jd1KGClEoJ8Yu4V0VbbAu03FDg4GJ70CcHoxWFNqWo2pe/24qRohuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-24T17:12:29Z"
    mac: ENC[AES256_GCM,data:aZUDaue/EJ1s99le3I5SIuapcpc1vXlIvS2N/NfCTp12DtIEEEuMlNzWRimip/PNHz3+NiOVPdY7+p4ZfcNMB6E7AtY2hnBgyeTQKYhFpHUqm/DllwX3yT4rEtosnqEUVz4GBBY4Y7NVTW86afbLBUpJTCpbC1qbz6YXYJR3P3o=,iv:k1dA/5+Wumz/PMuAgEuh0QrUKhzeDO93H/4xouSTLo0=,tag:Eqh+b4O0q4yGBjshDibScg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-backup-storage
    namespace: gitlab
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:HUpuKUdpAINOLAckHgLv8a9jay9EJQwNk8X7mfGuJKbsiVAVRnezZZ2Ae4ZMhqQhj3QhNhoY3l8aZLe3NHhFSmOBnKq53hToaCD6x6Wn4vnzJiFXFTAVmZsqmFtOq6pOvdS/44Prm1t+GXgq0tEVcdOzM/TG2adfH2hvX8FXb7F/iEqdAG8M7zdJQtL+85psZ+sQEBxOy4u+u+PUVzJSD9eNdCD6rPxEhWklURUViiSphvREcC+ZMiNy5eUOFFFyPBgpMblGmfxAmzPGRbmLRB4ffhPzYTsfW5Woz+dFWvrvCFCaYvaIRpOxjpM4P4l/dyS1wlsjw9BfVusGW41ld82eg2PFyeOq3miCAx9T7wtW4CaryfMmiEO88qwil8VsfOPUwdWsLCHlrushDi2GYb6i9isWSPja58JOSBP0swina6BtF/1rLaSMKk0=,iv:IQ5VqWNfSHK6J3ciyGW/4vZ610p+BVhx1IbEHSGNdfA=,tag:ScipHdfI0ifzedaa07wkfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUmZPcXpBUmw4ZEx6UzVQ
            WllIUlQxa1RORlk1Z2JOYnFzQUpTU1BXNW5nCjEreGd6aHYrL3MzcEhzemw3K08x
            RVl4cm8vQkYxRnl0TFBORlpkR1A5UzQKLS0tIHg3K3JWcW54akJ3WS9yK3dGdk1I
            ZWs2azRHNlY4S3NuRXN2WGtVeUFwSXcKtH4Av+52XbsTP9PEG2hK7WVzHOCAoQ7+
            Jd1KGClEoJ8Yu4V0VbbAu03FDg4GJ70CcHoxWFNqWo2pe/24qRohuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-24T17:12:29Z"
    mac: ENC[AES256_GCM,data:aZUDaue/EJ1s99le3I5SIuapcpc1vXlIvS2N/NfCTp12DtIEEEuMlNzWRimip/PNHz3+NiOVPdY7+p4ZfcNMB6E7AtY2hnBgyeTQKYhFpHUqm/DllwX3yT4rEtosnqEUVz4GBBY4Y7NVTW86afbLBUpJTCpbC1qbz6YXYJR3P3o=,iv:k1dA/5+Wumz/PMuAgEuh0QrUKhzeDO93H/4xouSTLo0=,tag:Eqh+b4O0q4yGBjshDibScg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-database
    namespace: gitlab
stringData:
    psql_password: ENC[AES256_GCM,data:IVSFbeMg2v2FwoqlobE8MQ==,iv:T5W3CDpu5pqIMxzUW6QYFa8labApRsRr57gEu2137Ws=,tag:YnpJEEOab31u0pZj/rYVBA==,type:str]
    redis_password: ENC[AES256_GCM,data:LoIWVk0POrklbRD5B033HgguW/dVhkwLWumpPFk67LOFq9hHe5czjIDmhEymcW61R29QLw2WwDjEuNnUX18=,iv:ilsoNnyTvd2HtNR6RraF1Wp12bbN7ucbIUnuHhDWSeE=,tag:V0yIAVrqJoFWlyTfketlNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUmZPcXpBUmw4ZEx6UzVQ
            WllIUlQxa1RORlk1Z2JOYnFzQUpTU1BXNW5nCjEreGd6aHYrL3MzcEhzemw3K08x
            RVl4cm8vQkYxRnl0TFBORlpkR1A5UzQKLS0tIHg3K3JWcW54akJ3WS9yK3dGdk1I
            ZWs2azRHNlY4S3NuRXN2WGtVeUFwSXcKtH4Av+52XbsTP9PEG2hK7WVzHOCAoQ7+
            Jd1KGClEoJ8Yu4V0VbbAu03FDg4GJ70CcHoxWFNqWo2pe/24qRohuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-24T17:12:29Z"
    mac: ENC[AES256_GCM,data:aZUDaue/EJ1s99le3I5SIuapcpc1vXlIvS2N/NfCTp12DtIEEEuMlNzWRimip/PNHz3+NiOVPdY7+p4ZfcNMB6E7AtY2hnBgyeTQKYhFpHUqm/DllwX3yT4rEtosnqEUVz4GBBY4Y7NVTW86afbLBUpJTCpbC1qbz6YXYJR3P3o=,iv:k1dA/5+Wumz/PMuAgEuh0QrUKhzeDO93H/4xouSTLo0=,tag:Eqh+b4O0q4yGBjshDibScg==,type:str]
    version: 3.13.1
