apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - kuberay-operator
  - soft-serve
  - tailscale-operator
  - trivy-operator
  - zot-registry
  - app-kustomization.yaml
