apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cloudflared
  - coredns
  - external-dns
  - flux-system
  - gitea
  - headlamp
  - kuberay-operator
  - tailscale-operator
  - traefik
  - trust-manager
  - woodpecker-ci
  - app-kustomization.yaml
