apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - connector.yaml
  - dns-config.yaml
  - proxy-class.yaml
  - proxy-group-policy.yaml
  - proxy-group.yaml
  - recorder.yaml
  - tailnet.yaml
