apiVersion: v1
kind: Secret
metadata:
    name: gitea-values
    namespace: gitea
stringData:
    values.yaml: ENC[AES256_GCM,data:ZmnaHe3AJ/wWCRq9Zwocdn5Cs855HtIZM+M55nfMn/F7qwUEqDm77p4Ki/HGWBCT+Ndp8EeGc3YvBACiP7/293xP1tKPyW7Nm5Ad2j1u/b0yjwKJx3KXlX5XktAyyIupsQuTn4xpGiEBtFUMkIpgqv9ptvVWOEy9peKtVjGyB5vgp+5Pdwm4gdUJZBdD4pHd7M6WJyR51BzlImLGlNuBBwv45EdbUmmJtcMf/IrNBTMk+boEXyN8GO1N+cOVSEOEgnlDCMTj+IeAR6jyZSEUnIPQjeP/dYLyFdDZfkJZIdp8ufGpLXepxeY7howckRSgfFazJ1ediGyBddplOMIORKXjdMLMvCkX5uLQ4iZonXFINoTMbdr2G+MNYG281KRT56GOqkOOZ1wg9wOcR8nBNDYbZhXa+FLagA1fRV152LvbxjCpo/cjIydeyuzMIU8xhFmfoV06xsin6MfhhmxaUhJNiWwkoOodQPjbWgzmzFU+XkHzAqBs7W7dSaM8fNpbyLbFv+mCAIMnXaiOk5jZwj8OAHUPMP04JtQCV3bejM882uvq2wJuUv9fwyJbvCQRyJEQ5hoC,iv:KS1VSk/zhKCSHJ3PjTM3uaGBJlnQV4hvrZG7djn7mVc=,tag:9rotMNew/2kf7dluHXHOdg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOERVYWxUcHFqN3NFVlQ0
            ZWZDRG1ZSEdvMTZjNjhHOXNUZmJRQWFiMkVvCllkK092a0d4ekJmL0RKL0wzM0ph
            THUxZG1WSzk0SFJTOW53RmlZSTZjcG8KLS0tIDROL2NsNDhsNVNucmdNWkNaVGNL
            TFMySXdTTkdpQTN1NU92T2ptalhtVVEK5+WuRrPhsIxIwEbYDy3rhlQpwP6CqqI+
            chgzSDVjqM9qUfWrg2hAxqyTn2Bayy38N/p73htiSLvfixKyevEZAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-09-15T16:09:02Z"
    mac: ENC[AES256_GCM,data:5u3p0Wre7z2SwZMUvH3zniTXDQCJ6Ui2hmSJcOogChhj7yOqx8WC3o/+vA2FAdNrN+QqvtaSO+0c0i2yv7HJHkO2CEsdXTtxQsNpbF7FsMiLfRfPXoFooPsEB/HNvYiSg4b+/nTAxbDbCqquu6hcWijBaXKVBnrGFT4egmW+9lA=,iv:EPbshEid3kObezkavdOZnZI4/jp6wdN7Q1HylfEn2kc=,tag:HGPQAhv7q4aGYpJd5lM8qg==,type:str]
    version: 3.13.3
