apiVersion: v1
kind: Secret
metadata:
    name: gitea-values
    namespace: gitea
stringData:
    values.yaml: ENC[AES256_GCM,data:NtM1ubHPEhXWIqxJnzJgXx4UysOUqVVWNAoqJgMtxLw11WPrPcXkYbwQ/q2TeTt5ksaSVlc5HryK2ifHBPygVepQI7Sf5X1YQ0RvFvZmJhs8Y2k7GidJLwGjvRpFirFqriC4FL3QUP5QvNQJ2/y1wy3Yd3UH8YaoDsqRApCm/C8kqJP+nvy3jrzjKxoGpCQSzSb7RuP/yf/WmmuZZGv8t9YPZFK5prS5s9bRHVDblC6Z7akcnxBz2r51637FdxXD7AItRicy56iS6wANFuqOCNFrRyKRnioCGpZev6bFrgKoow7ykVEG3OoFl+Q9nBTho33iJGBDPC87tCua+aXV4zQnSxJ7O8lIp9i1B65zwus9ASqhHs4T3ss37yqyOuPSPzMh4TAR5xcsV5k8zHtjcpn5B4MWXbAfc0AJszAgMgsiYRebfYTQZGGH9fDDGeJCq770mk2/0jnURnKp0Z50aCXkxt0LxV9hUEYK0mRtw87VgV5Up/V3gKoYDKXNCGy+kfUFFMGKxLUa/u5F0LJcUkHilqretQEOMMWCc8wVwjdx4ekBf7v3LxonCcJe0c+cq5UoNPS/3Bt/aPDj32XWb3cS,iv:eZsvkONBR6KZCALhnXSCSZCBH5MZRsmC4PXyBlzbaNA=,tag:S1USAi906RmO09B10UTNkw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOERVYWxUcHFqN3NFVlQ0
            ZWZDRG1ZSEdvMTZjNjhHOXNUZmJRQWFiMkVvCllkK092a0d4ekJmL0RKL0wzM0ph
            THUxZG1WSzk0SFJTOW53RmlZSTZjcG8KLS0tIDROL2NsNDhsNVNucmdNWkNaVGNL
            TFMySXdTTkdpQTN1NU92T2ptalhtVVEK5+WuRrPhsIxIwEbYDy3rhlQpwP6CqqI+
            chgzSDVjqM9qUfWrg2hAxqyTn2Bayy38N/p73htiSLvfixKyevEZAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-09-15T17:30:22Z"
    mac: ENC[AES256_GCM,data:npCyreWvl/Wika/d2y8vqBTdOgrIT5MGR9jSuSCMs8+koqAiX1h1UHt1IADtUngHSGkYRTP0tqJ8TY+vDFXAGBTKz1qL4V45hQTY2HdKWCKhj6MAg6D15j3ZirAxwpqg8ObouiNbVKUQbl3VeEpExRRFS5mLSocyMYQ6d5wPfco=,iv:bdlCg8pffVZyIIKIrSRgO+bL7y2O4KWQGpJPZ3Wmyrk=,tag:0pn/QFEnH0ZQD7sg58vTew==,type:str]
    version: 3.13.3
