apiVersion: v1
kind: Secret
metadata:
    name: gitea-admin
    namespace: gitea
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:7f2kgk7qK8WI9jk=,iv:7/2+OS9ZJmAL1xo4ZmeM1I4b902XLFzCMPgeAcH5GfU=,tag:yGfDfxx7O4wjY+RbVRaA/Q==,type:str]
    password: ENC[AES256_GCM,data:JsxCYV4QIJFhLetrENWwLEQDijP+VjWBAvYdqlviVEcuhaA9Rx9SDmWiKyjksY44,iv:f4vBSPCVQjVD0HaxJK2+9a5+5eWbV/Amg4zldkOEkWo=,tag:sLI/XAUMET9eCjJyQAe7AQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMWxKMmpoandPYm5iZHpm
            U2VGT2FWN012eXlrSTd3VkxQMWJ2UW5mbzJjCmFFdElFeEZjNDMxR3p5S3VXYmds
            OW9CQ09WMld3dE5TcnZSQmhIUWR1Q0UKLS0tIHFKckVySFF1R1VGMUV6Ty94bERm
            a3k5V2ZEdHpsV042WEQ2UklSeW5ZM0UKJR1g3MntL0m/oEeVVrAYU8RD2ZFixzUi
            EyfdXLhNYveyv/zDMILIYNJzm4uW2ErOjeFF+lI0xct3KxfBkhmahw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-09-15T15:33:23Z"
    mac: ENC[AES256_GCM,data:Knja5TkXYuLdLpdpUnifOhG8zG6rNs5lU0/xfpMFcpoZm+K7v/viwDxt7u8ap9X/fCK5SO/6MoC4Ek7nZV7NLgApja0dn6OFYUkEguto3XNZytxoTNBxqjQrX25x9pKTAqV04gmGSxGinNgvni8S42/zjVQrbzdpkwcHPqMLETQ=,iv:JKJmKaetWb1yLeQ8/dyr6PcQssF8xh9DjDpWJSAlcZw=,tag:Z/XhD+Jc3kTXXRGb8kaGmw==,type:str]
    version: 3.13.3
