apiVersion: v1
kind: Secret
metadata:
    name: gitea-values
    namespace: gitea
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:k57bvWplXJR4eScjQKkvdvBWxIdpdUhndoUP1djDnzTApcadPRRGq3TDqu4atpa6Aur+QyCQd5/xoxsb3eDj+T0dyd0g+74xM7GdHwCNvR+onopBPE8/shF08vZN2H8FsvV196c1Fcf3qD30l6UIBAW7nO/m1lOnZxk00L3lbPo1GumcrollPF9Yi6MmCXMkzPGwrxcvQCCiPlvnp0IZoNeEDPqIsxrVTjhHKrkq/kkfcQVTGFwyreG12ECDe5qD9UZX+zxIcfcEpky+WgXd6mX4zY18mmD7oashYQIxN81JJOFFTHTuxlXD4T0=,iv:mhNrKyAgumqOA1hy9VA+9+4SzVOtx7seT3asoShTB+A=,tag:/Ws34O/6x77wYpjYb5KKyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SGdnbkNEV08xcHI2T3BO
            Y1h2aVQ1SXRCVjF5MStmTi9ObFJncDl0a0QwCnl2YTFlYm5ueGpOSnZkRlNYTVB6
            eGlkNG90MFhxNnNlTGk5QXJNdmRwOEEKLS0tIC83S09nS1FoYnRPL21PN3Bkd2Za
            WmEzcG9QKzFYWGJvZGh5WDZqWG9TZTQK8dNTXdwREOJ+d43sDc6JFG4Azrf33lkw
            4uh2i5AFlOYhAclRFyoK61w6tnarA9DMRRKvzFGFoKx+fxoOK2Wjhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-05-24T11:54:47Z"
    mac: ENC[AES256_GCM,data:4wlOe8+TOgHfU32sJ2c+viXtLPWDu4zBZPR4+kaPYPpPfKjrYcT24z0ptIbrqY9XEn2Y1nFGpvnD6Zb20ZC0X9wG4yWg24afJwwrxEnBnS6m00tfSjbDPa9a4qbq9i2oYV7Fjza3ElsmxRSfwoXj7dDt1cPER4NrtivQfoFXiy8=,iv:VcRXpGlicbVxbPGP3tbtQYiAs/+MQT9CgptDrXHe0F4=,tag:EEDFwgRPO6QceesrL0Ei4g==,type:str]
    version: 3.13.1
