apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - crd
  - deployment.yaml
  - service-account.yaml
  - ingress-class.yaml
  - role.yaml
  - cluster-role.yaml
