apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:7016wjHDkp7uoRyotA4rC7c=,iv:jeTMFGksU/s2/znCUlFsyzyIOI6jv+Xmc2704qCucwY=,tag:BRC7TNwdyDC9ZT0tGFezgA==,type:str]
    client_secret: ENC[AES256_GCM,data:cpJD8OEacWBqJVf+J9x1YHDKyous+p7k/XWeSCCq5iKSBC2fiaNrHFNT6vXOhnmGde13eoh7pn2rlc3g0N3U,iv:hu2u87uZtOsSUHEawxGIumyOaqs7qAaIgi82SOBNegw=,tag:IYG1Qk3KiOqOMJCpBGfWBQ==,type:str]
sops:
    age:
        - recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Qk1JSWtMWlYrdG1Mb1FJ
            ODhXTm41dkl5VFhHcFZqUDhUK1N1UVh6RzFBCnBnb1hDYWd2am4rRlJ1T09Td0hJ
            YWViL1lVSnJGR1dWS0lTcDFhakJ1ZUEKLS0tIEZoQ0pEL2pPTnUyNVFUWmM0TGRT
            bklzbzQvN1RRYVh0UXNQcU01aVFSbEEKEGamU+4y5ZgE45XW3ikvDQ7G2Iq1W3/I
            5pTburslXguq04jJbCgjANb/3z+gyrYIN2Zkom6tgc0+o2Tgv5LXCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T09:44:24Z"
    mac: ENC[AES256_GCM,data:yqwiyAsgjXAjz3U+sn3wFmKeFT49lbqvu2wvtlwL8PSIMq3/U2i5zZJYgNhqFw8CF9GdIYM9qyhOGJfKLJ5qXKz5aUXt3LyiNxNhUwgOqPzhHcPhqmp05C2cM3QKBzy77yG09byWuJKnOe0ycc1QAyWIjZnd32FcOb+MifKywMc=,iv:HtHbUPfkdRen964H4XzVrP9JXFbOoLzYkXPwGqp7/7E=,tag:kfzxvx7QTVDrL7QUNS6mcg==,type:str]
    encrypted_regex: ^(data|stringData)
    version: 3.12.2
