kind: Secret
apiVersion: v1
metadata:
  name: headlamp-operator
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "headlamp-operator"
type: kubernetes.io/service-account-token
