apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:enacv7hVE6PS18th/S8581BdeY9bIT0IA1WeEsy9OUK7eW9QoHRqI8Q+tvAFVD5FgGJm5dJuUBkqnEFh+Y8S2SHefOU3Qdzc6YsahYamyD/G1F8ByfGTm1P6s3e6aQPTDGVCEs5urzIcrtrjF2ismdDnRuGmbf0L4eAbD2aGSRiocAk4owfN0OvyTezmx6tFYQqWS5rw6ulo/q97mErPlNNykWRlwe6tLqRSep0dK9TIfbgZMQ2nMQ==,iv:NZIx/7LALPEzcYkMY2j2kga+lAPCSzQcEirl5U4g3Cg=,tag:CqRpOSyqZIf2Cx+7SKAKdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM1ZQalhGNHFuWFJCVks3
            T2lPdzlyNmpsNXZPUVlKMVB0aExjUWV0WkFRCktSVFZXREZhYy94eWx5ZlpFeWRy
            cVhQZk50cFRURysyQUcxTmVzek9PQ28KLS0tIGROTUtPUDYwRjl3dmhyZXZiTDN6
            czJmdGwvS2FrWkNyL3BZRjVpY3h0UlEKKDvgp7cUye7eUbADYN9uYAFkiOtBZGCj
            6JuHjf7JW7MEwcZOTqPXeyCqThSiRgMT9mvdPO7tegahaO+AaVUMyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-09-16T14:03:27Z"
    mac: ENC[AES256_GCM,data:3/Zp2bWJ1ZHoEeyYjAy9nG8PEjyiA+jPLLu7Ar6soOgo1vkFfTsHWEChld29o3eh9QjEctyVJHSywBtrMlOaIcupuhCqwZRDEZsNtXJVQBHRkI3yOtImVZI+V0vQnbBapd17rPCd8if4wUTxPQ2sSL0nRXB9nEQL5V9C2ep7WA8=,iv:nbOkVKVMBQhJDaZB/kDJG7QL0DTNQDK5Yk1YCTUts/0=,tag:8lKntz4EC9paDOgSzVlw+w==,type:str]
    version: 3.13.3
