apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: external-dns
type: Opaque
stringData:
    tsig-keyname: ENC[AES256_GCM,data:KHQIBHpg9gEYBvae,iv:tuLsudV2x8b0pwE6xC/TrnDT8/VuTRwKqcguqkSqg18=,tag:riYciLiM9nwRy9iLijV2OA==,type:str]
    tsig-secret: ENC[AES256_GCM,data:LMqF3yYcgbMpV9QHcmyLerVqPkzJxajp9nVIFUaw1D5SZLOp0uybKAokRIA=,iv:InlIFLVQtjLagw8n4e6SjsWnX84Eb0+hzbBc4hdHzvM=,tag:JUTW7O2a4GmPUqTCB8GE5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbUN6dk1tYTZxU0dIaFNK
            cnl3amgxNm5oQTZSeitjS09Nb1dpQ0hNN0MwCmVoYWZmSlFqOEE2TGVuUlRJcmlm
            dWFjRTlIUjVTT2piT2RwN3pleitSaDgKLS0tIEQ3SGVzQWdpS2tUdTZPY1ZURUo4
            cE15ZGQzalNSaXY3YUUyaEFCbFRaeUEKbKwWRgNzGQj3Ao2UmkB/ielUzT/2O75p
            7g/JxzUePep474fu5G2HXGG1WDfuc4DGpNXuFV2rCTDfZb1ouaMyNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-08-28T13:41:25Z"
    mac: ENC[AES256_GCM,data:njdRYFsrRIRGd14p2aCGYzExcc9KE9CPjcCeYM/DUNTSV85IDxEIYbcBRtB1iioEmzLKWNTSdcSTmsbuUSKimNnMydGwbGc3s3AOiZnmLXerBogOJ3M7f+bm1va2q84McOjSYLNegi773qzt7tNtSyV5xgIVjqMyfAF2GtuAjeE=,iv:Ar0JItPRijNCJd+2Z48FjNDVtceU4NaurDpgcBPmuug=,tag:BPvIOZ76F8o711UrYWiVzA==,type:str]
    version: 3.13.3
