apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: external-dns
type: Opaque
stringData:
    tsig-keyname: ENC[AES256_GCM,data:06fAW7qMqGY1q10B,iv:RKa7VbZlGSSUdQF56/na1bHzVnm0czqv2FGA13aUB94=,tag:cAfTbJfs1Rtt9HFwJ8ZAzQ==,type:str]
    tsig-secret: ENC[AES256_GCM,data:LTdojAyf3+zjC3nbmrJ/17T2atgW1JpYWp/V6FcL6bGI+uMfi4GiPZmh3fM=,iv:YNGzLi0BByPFvjAy3LDCgrQo+4//vbC7wpUPsnYjIrQ=,tag:c4Xm9QOKe/ayczPD9PRZ8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMGR4Z3o4V1JRUjlDeGlt
            cG03dm5nWFp0SEZqSXphZmF2NFl0dUtrYlN3CkZ0SFJTZFY0U09NdXA2OHJQU0lJ
            MUo0cmZzTGptdm02TTNZQWM2eElubDgKLS0tIDFpWUYxUjZsdnZ0MUdnSmhkeWNs
            YzdBTWk1ekxaZGhqSmFMZmlLQS8zWU0K2olcuhlvLI9veB1Wq95t40+vZFAEd9he
            J3d+tHgBXYnzCIsik1pnBTirsjCm47coBaXdVCVWqkDULkX8TKIjGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-09-09T17:13:44Z"
    mac: ENC[AES256_GCM,data:kxBkDyaxngmX9ycO42u6u6M2XGQTRZGVMei+ylBGql11RLvQsRWjrHDFeHh5FXGkK5xYQsiPTiNEBo8VgUk2XD4StUxfQk6n6KO/irU3pfimDvcDTKflLuN/0Gp6Z1I/o2riobOcKluzT9wGE2EOVnmWSOq5pq/1q8jhiW9QLs4=,iv:uKagGswQ/IuHTD10eW1W6qyDTw8T1opGgoeR4fJxjOM=,tag:jLVvxjtj52pJbF6/4i6jjA==,type:str]
    version: 3.13.3
