apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: external-dns
type: Opaque
stringData:
    tsig-keyname: ENC[AES256_GCM,data:cb7JVHEkrMQP0Xnk,iv:bF1MZeLXrNz4KJWaMhLYWwn7X0YFxYA8PxYZPEwZhjw=,tag:2eKZm32GU7BXC4RFDKKhVA==,type:str]
    tsig-secret: ENC[AES256_GCM,data:vbs80TqaA7T0/zX+BR338jMB/PDzGL4k5QpQj/g6ZMNDlwYXCduHNfpzyek=,iv:nn185GlxOA4n4t6ZFgAvD3rMyZmoydPNH9gaiNmTtMg=,tag:yu6tW+htHMYSVrNNyr9KCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSG9kbGdPOHFMbUplL0pB
            bXdNQ2FBMDJMSEZRQVRyS0t6TUpaZ3dpTUFRCkxGSTZRRWVhdzNDRjFKVE1tczk5
            b2w2bFc1V2Q0R091a0g1RFhEalJibGcKLS0tIHltWkpzMUpWZktITVlycTE5eDh5
            bS95SFFhd1RjM2pZQW9yaUhwU3pMQ1EKZHbdq9rPW5NihBJvzUE+JvA+XpRWALBV
            J2axiJ3amNHUvFDHgNdjZ4W/vB/ynRIav1l8LmSkNp5+YNOreNIceQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17wu0vazr0uhje3m2rpdxn52k2wxfmwgakrt3ftmgacyz0whhep8shrswx4
    encrypted_regex: ^(data|stringData)
    lastmodified: "2026-09-09T15:59:09Z"
    mac: ENC[AES256_GCM,data:xNnUVCfFevF9+8VMBshI+vTqvtDPAWHwZboCUEcI1+IgJ8MOIHKKzcTqKTwtgE9woYbulJe2y1s17CSr9aUSvW/QJIZk14AicbDtyq5KTRyiqn5DqAa0/9XsNbE2c6K+Jc7cc1Xgq1hP9blWiu5/hHYfQPksAPNTqFkHwcFRrmQ=,iv:lYkN3n/AJ0Da9O8919ViGiR8fRQpHylh5hrNr+ySnZ0=,tag:Tl/e62+xoQ2NIcYZVN+Vuw==,type:str]
    version: 3.13.3
